#!/usr/bin/python3
from sys import argv

with open(argv[1]) as f:
    for line in f:
        number = int(line)
        print("{:d}=".format(number), end='')
        if number % 2 == 0:
            print("{}*2".format(number//2))
            continue
        for i in range(3, number, 2):
            if number % i == 0:
                factor = number//i
                for j in range(3, factor, 2):
                    if factor % j == 0 or j == 0:
                        break
                print("{}*{}".format(factor, i))
                break
